eureka:
  client:
    service-url:
      defaultZone: http://120.78.88.169:8761/eureka,http://120.78.88.169:8763/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          # 是否与服务发现组件进行结合，通过serviceId转发到具体的服务实例。默认为false，为true代表开启基于服务发现的路由规则。
          enabled: true
      routes:
        # -----------------------鉴权模块----------------
        - id: auth-service
          # 路由指向具体的服务实例
          uri: http://127.0.0.1:8768
          # 带指定请求头的URL转发到相应的服务实例
          predicates:
            - Path= /oauth/*,/auth/*
#          filters:
#            # 对请求进行截断
#            - StripPrefix= 1
#            - name: Retry
#              args:
#              retries: 3
#              fallbackUri: 'forward:/fallback'
        - id: user-service
          uri: http://localhost:8001
          predicates:
            - Path= /user/*

#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/oauth/token
      user-authorization-uri: http://localhost:${server.port}/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri:  http://localhost:${server.port}/auth/user
      prefer-token-info: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3500

server:
  port: 8763
