eureka:
  instance:
    hostname: localhost
    statuspageUrl: http://localhost:8768/index
  client:
    serviceUrl:
      defaultZone: http://120.78.88.169:8761/eureka,http://120.78.88.169:8763/eureka

spring:
  application:
    name: auth-service
  redis:
    database: 0
    host: 120.78.88.169
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.88.169:3306/file?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 69C467895aab
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8768

#
logging:
  pattern:
    level: INFO
